from fpdf import FPDF

# --- PDF GENERATOR ---
class IFRACertificate(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.cell(0, 10, 'CERTIFICATE OF CONFORMITY', align='C')
        self.ln(5)
        self.set_font('Helvetica', '', 10)
        self.cell(0, 10, 'INTERNATIONAL FRAGRANCE ASSOCIATION (IFRA)', align='C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

def create_ifra_pdf(product_name, client_name, date_str, dosage, data):
    pdf = IFRACertificate()
    pdf.add_page()
    pdf.set_font("Helvetica", size=10)
    
    # Info Block
    pdf.set_font("Helvetica", 'B', 10)
    pdf.cell(35, 7, "Product Name:", 0)
    pdf.set_font("Helvetica", '', 10)
    pdf.cell(0, 7, product_name, 0, 1)
    
    pdf.set_font("Helvetica", 'B', 10)
    pdf.cell(35, 7, "Client:", 0)
    pdf.set_font("Helvetica", '', 10)
    pdf.cell(0, 7, client_name, 0, 1)
    
    pdf.set_font("Helvetica", 'B', 10)
    pdf.cell(35, 7, "Date:", 0)
    pdf.set_font("Helvetica", '', 10)
    pdf.cell(0, 7, date_str, 0, 1)
    pdf.ln(10)
    
    # Declaration
    text = (
        "We certify that the above compound is in compliance with the Standards of the "
        "INTERNATIONAL FRAGRANCE ASSOCIATION (IFRA), 51st Amendment to the IFRA Code of Practice "
        "(published June 2023), provided it is used in the following class(es) at a maximum concentration level of:"
    )
    pdf.multi_cell(0, 5, text)
    pdf.ln(5)
    
    # Class Limit
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(0, 10, f"IFRA Class 4 (Fine Fragrance): {dosage}%", 0, 1, 'C')
    pdf.set_font("Helvetica", '', 10)
    pdf.ln(5)
    
    # Restricted Materials Table
    results = data.get('results', [])
    restricted = [r for r in results if r['limit'] != 'Specification' and r['limit'] is not None]
    
    if restricted:
        pdf.set_font("Helvetica", 'B', 10)
        pdf.cell(0, 8, "Restricted Ingredients Detected:", 0, 1)
        pdf.set_font("Helvetica", 'B', 9)
        
        # Table Header
        col_w = [90, 40, 40]
        pdf.cell(col_w[0], 7, "Material / Standard", 1)
        pdf.cell(col_w[1], 7, "Level in Formula", 1)
        pdf.cell(col_w[2], 7, "IFRA Limit", 1)
        pdf.ln()
        
        pdf.set_font("Helvetica", '', 9)
        for r in restricted:
            name = str(r['standard_name'])[:50]
            conc_str = f"{round(r['concentration'], 4)}%"
            limit_str = f"{r['limit']}%"
            
            pdf.cell(col_w[0], 6, name, 1)
            pdf.cell(col_w[1], 6, conc_str, 1)
            pdf.cell(col_w[2], 6, limit_str, 1)
            pdf.ln()
            
    pdf.ln(10)
    
    # Disclaimer
    pdf.set_font("Helvetica", 'I', 8)
    disclaimer = (
        "The IFRA Standards regarding use restrictions are based on safety assessments by the "
        "Panel of Experts of the Research Institute for Fragrance Materials (RIFM) and are "
        "enforced by the IFRA Scientific Committee. Experimental data is presumed to be accurate "
        "but is not guaranteed."
    )
    pdf.multi_cell(0, 4, disclaimer)
    pdf.ln(5)
    
    pdf.cell(0, 8, "Automatically generated by miniPinscher IFRA Engine", 0, 1, 'R')
    
    return bytes(pdf.output())
